

version: '2.1'

services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - ./env/local.env
#    volumes:
#      - ./.pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5