"""add merchant

Revision ID: 729c4de2c96e
Revises: 58ab8ec8d14a
Create Date: 2021-09-25 21:47:02.256274

"""
from alembic import op
import sqlalchemy as sa
import dbo_models

# revision identifiers, used by Alembic.
revision = '729c4de2c96e'
down_revision = '58ab8ec8d14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickup',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merchant_id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('pick_up_id', dbo_models._helper.GUID(), nullable=True),
    sa.Column('delivery_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('order_id', dbo_models._helper.GUID(), nullable=True),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['pick_up_id'], ['pickup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('menuitemtoaddongroup_addon_group_id_fkey', 'menuitemtoaddongroup', type_='foreignkey')
    op.drop_constraint('menuitemtoaddongroup_menu_item_id_fkey', 'menuitemtoaddongroup', type_='foreignkey')
    op.create_foreign_key(None, 'menuitemtoaddongroup', 'addongroup', ['addon_group_id'], ['id'])
    op.create_foreign_key(None, 'menuitemtoaddongroup', 'menuitem', ['menu_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menuitemtoaddongroup', type_='foreignkey')
    op.drop_constraint(None, 'menuitemtoaddongroup', type_='foreignkey')
    op.create_foreign_key('menuitemtoaddongroup_menu_item_id_fkey', 'menuitemtoaddongroup', 'menuitem', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('menuitemtoaddongroup_addon_group_id_fkey', 'menuitemtoaddongroup', 'addongroup', ['addon_group_id'], ['id'], ondelete='CASCADE')
    op.drop_table('delivery')
    op.drop_table('pickup')
    op.drop_table('merchant')
    # ### end Alembic commands ###
