"""empty message

Revision ID: 02d79e3a9003
Revises: f2a0430e139d
Create Date: 2021-11-05 16:57:50.673640

"""
from alembic import op
import sqlalchemy as sa
import dbo_models


# revision identifiers, used by Alembic.
revision = '02d79e3a9003'
down_revision = 'f2a0430e139d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('order_id', dbo_models._helper.GUID(), nullable=True),
    sa.Column('payment_intent_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('client_secret', sa.VARCHAR(length=100), nullable=False),
    sa.Column('receipt_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
