"""promotion_type

Revision ID: 19a564bc9220
Revises: 8f947749424f
Create Date: 2021-07-27 20:33:49.261676

"""
from alembic import op
import sqlalchemy as sa
import dbo_models


# revision identifiers, used by Alembic.
revision = '19a564bc9220'
down_revision = '8f947749424f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotiontype',
    sa.Column('promotion_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotiontype')
    # ### end Alembic commands ###
