"""added_orders

Revision ID: 58ab8ec8d14a
Revises: 5cf83e20d692
Create Date: 2021-09-09 16:58:49.467124

"""
from alembic import op
import sqlalchemy as sa
import dbo_models


# revision identifiers, used by Alembic.
revision = '58ab8ec8d14a'
down_revision = '5cf83e20d692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('street', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=20), nullable=True),
    sa.Column('state', sa.VARCHAR(length=15), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('reward_point', sa.Integer(), nullable=True),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('customer_id', dbo_models._helper.GUID(), nullable=True),
    sa.Column('payment_token', sa.VARCHAR(length=100), nullable=False),
    sa.Column('promo_code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tax_multiplier', sa.Float(), nullable=True),
    sa.Column('tip_multiplier', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    op.create_table('orderitem',
    sa.Column('order_id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('special_instruction', sa.VARCHAR(length=100), nullable=True),
    sa.Column('menu_item_id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menuitem.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitem_menu_item_id'), 'orderitem', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_orderitem_order_id'), 'orderitem', ['order_id'], unique=False)
    op.create_table('addontoorderitem',
    sa.Column('order_item_id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('addon_id', dbo_models._helper.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addon.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['orderitem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id', 'addon_id')
    )
    op.create_index(op.f('ix_addontoorderitem_addon_id'), 'addontoorderitem', ['addon_id'], unique=False)
    op.create_index(op.f('ix_addontoorderitem_order_item_id'), 'addontoorderitem', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addontoorderitem_order_item_id'), table_name='addontoorderitem')
    op.drop_index(op.f('ix_addontoorderitem_addon_id'), table_name='addontoorderitem')
    op.drop_table('addontoorderitem')
    op.drop_index(op.f('ix_orderitem_order_id'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_menu_item_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_table('order')
    op.drop_table('customer')
    # ### end Alembic commands ###
