"""empty message

Revision ID: aa54e6a49c55
Revises: 58ab8ec8d14a
Create Date: 2021-09-20 16:11:16.432246

"""
from alembic import op
import sqlalchemy as sa
import dbo_models


# revision identifiers, used by Alembic.
revision = 'aa54e6a49c55'
down_revision = '58ab8ec8d14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('menuitemtoaddongroup_menu_item_id_fkey', 'menuitemtoaddongroup', type_='foreignkey')
    op.drop_constraint('menuitemtoaddongroup_addon_group_id_fkey', 'menuitemtoaddongroup', type_='foreignkey')
    op.create_foreign_key(None, 'menuitemtoaddongroup', 'menuitem', ['menu_item_id'], ['id'])
    op.create_foreign_key(None, 'menuitemtoaddongroup', 'addongroup', ['addon_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menuitemtoaddongroup', type_='foreignkey')
    op.drop_constraint(None, 'menuitemtoaddongroup', type_='foreignkey')
    op.create_foreign_key('menuitemtoaddongroup_addon_group_id_fkey', 'menuitemtoaddongroup', 'addongroup', ['addon_group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('menuitemtoaddongroup_menu_item_id_fkey', 'menuitemtoaddongroup', 'menuitem', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.drop_table('merchant')
    # ### end Alembic commands ###
