"""pomotions

Revision ID: c43b11d1301d
Revises: 19a564bc9220
Create Date: 2021-07-28 15:20:18.243987

"""
from alembic import op
import sqlalchemy as sa
import dbo_models

# revision identifiers, used by Alembic.
revision = 'c43b11d1301d'
down_revision = '19a564bc9220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion',
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('promotiontype_id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('promo_code', sa.VARCHAR(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promotiontype_id'], ['promotiontype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_promotiontype_id'), 'promotion', ['promotiontype_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotion_promotiontype_id'), table_name='promotion')
    op.drop_table('promotion')
    # ### end Alembic commands ###
